### ISSUE TITLE
Shell terminal transparent

### ISSUE THREAD

**Issue by NicoHood** [jnsh/arc-theme#81] opened 2020-09-26 15:35 UTC
Hey there!
After some recent update of ArchLinux, my terminal is now transparent. This does not happen with the default gnome theme:

![image](https://user-images.githubusercontent.com/6888294/94344270-63e67a80-001e-11eb-9253-ef65e3d33dc8.png)

I've upgraded the following packages:
```
[2020-09-26T17:23:13+0200] [ALPM] upgraded filesystem (2020.08.21-1 -> 2020.09.03-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded e2fsprogs (1.45.6-2 -> 1.45.6-3)
[2020-09-26T17:23:13+0200] [ALPM] upgraded perl (5.32.0-1 -> 5.32.0-3)
[2020-09-26T17:23:13+0200] [ALPM] upgraded openssl (1.1.1.g-2 -> 1.1.1.h-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded libldap (2.4.50-2 -> 2.4.53-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded libuv (1.39.0-1 -> 1.40.0-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded nodejs (14.10.1-1 -> 14.12.0-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded glib2 (2.64.5-1 -> 2.66.0-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded nspr (4.28-1 -> 4.29-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded systemd-libs (246.4-1 -> 246.6-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded nss (3.56-1 -> 3.57-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded srt (1.4.1-2 -> 1.4.2-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded ca-certificates-mozilla (3.56-1 -> 3.57-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded libelf (0.180-1 -> 0.181-1)
[2020-09-26T17:23:13+0200] [ALPM] upgraded vulkan-icd-loader (1.2.151-1 -> 1.2.153-2)
[2020-09-26T17:23:14+0200] [ALPM] upgraded mesa (20.1.7-1 -> 20.1.8-1)
[2020-09-26T17:23:14+0200] [ALPM] upgraded libva (2.8.0-1 -> 2.9.0-1)
[2020-09-26T17:23:14+0200] [ALPM] upgraded rav1e (0.3.3-1 -> 0.3.4-1)
[2020-09-26T17:23:14+0200] [ALPM] upgraded systemd (246.4-1 -> 246.6-1)
[2020-09-26T17:23:15+0200] [ALPM] upgraded json-glib (1.4.4-2 -> 1.6.0-1)
[2020-09-26T17:23:15+0200] [ALPM] upgraded dconf (0.36.0-1 -> 0.38.0-1)
[2020-09-26T17:23:15+0200] [ALPM] upgraded pango (1:1.46.1-1 -> 1:1.46.2-1)
[2020-09-26T17:23:15+0200] [ALPM] upgraded libgudev (233-2 -> 234-1)
[2020-09-26T17:23:15+0200] [ALPM] upgraded brotli (1.0.7-3 -> 1.0.9-2)
[2020-09-26T17:23:15+0200] [ALPM] upgraded gsettings-desktop-schemas (3.36.1-1 -> 3.38.0-1)
[2020-09-26T17:23:15+0200] [ALPM] upgraded glib-networking (2.64.3-2 -> 2.66.0-1)
[2020-09-26T17:23:20+0200] [ALPM] upgraded atom (1.50.0-1 -> 1.51.0-1)
[2020-09-26T17:23:20+0200] [ALPM] upgraded bind (9.16.6-1 -> 9.16.7-1)
[2020-09-26T17:23:20+0200] [ALPM] upgraded chromium (85.0.4183.102-1 -> 85.0.4183.121-1)
[2020-09-26T17:23:20+0200] [ALPM] upgraded cifs-utils (6.10-1 -> 6.11-1)
[2020-09-26T17:23:21+0200] [ALPM] upgraded cmake (3.18.2-1 -> 3.18.3-1)
[2020-09-26T17:23:21+0200] [ALPM] upgraded code (1.49.0-2 -> 1.49.1-1)
[2020-09-26T17:23:21+0200] [ALPM] upgraded imagemagick (7.0.10.29-1 -> 7.0.10.30-1)
[2020-09-26T17:23:21+0200] [ALPM] upgraded cups-filters (1.28.2-1 -> 1.28.3-1)
[2020-09-26T17:23:21+0200] [ALPM] upgraded dolphin-emu (1:5.0.r12443.b5241d1c2c-1 -> 1:5.0.r12660.39df01434c-1)
[2020-09-26T17:23:22+0200] [ALPM] upgraded dotnet-host (3.1.7.sdk107-1 -> 3.1.8.sdk108-1)
[2020-09-26T17:23:22+0200] [ALPM] upgraded dotnet-runtime (3.1.7.sdk107-1 -> 3.1.8.sdk108-1)
[2020-09-26T17:23:22+0200] [ALPM] upgraded netstandard-targeting-pack (3.1.7.sdk107-1 -> 3.1.8.sdk108-1)
[2020-09-26T17:23:22+0200] [ALPM] upgraded dotnet-targeting-pack (3.1.7.sdk107-1 -> 3.1.8.sdk108-1)
[2020-09-26T17:23:23+0200] [ALPM] upgraded dotnet-sdk (3.1.7.sdk107-1 -> 3.1.8.sdk108-1)
[2020-09-26T17:23:23+0200] [ALPM] upgraded elfutils (0.180-1 -> 0.181-1)
[2020-09-26T17:23:23+0200] [ALPM] upgraded enchant (2.2.8-3 -> 2.2.10-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded firefox (80.0.1-1 -> 81.0-2)
[2020-09-26T17:23:24+0200] [ALPM] upgraded fluidsynth (2.1.4-1 -> 2.1.5-2)
[2020-09-26T17:23:24+0200] [ALPM] upgraded ghostscript (9.53.0-1 -> 9.53.2-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gobject-introspection-runtime (1.64.1-2 -> 1.66.0-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gpm (1.20.7.r27.g1fd1941-2 -> 1.20.7.r38.ge82d1a6-2)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gradle (6.6-1 -> 6.6.1-2)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gstreamer (1.16.2-2 -> 1.18.0-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gst-plugins-base-libs (1.16.2-2 -> 1.18.0-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gst-libav (1.16.2-2 -> 1.18.0-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gst-plugin-gtk (1.16.2-3 -> 1.18.0-1)
[2020-09-26T17:23:24+0200] [ALPM] upgraded gst-plugins-bad-libs (1.16.2-13 -> 1.18.0-2)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gst-plugins-good (1.16.2-3 -> 1.18.0-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded libde265 (1.0.6-1 -> 1.0.7-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gupnp-igd (0.2.5+3+gedd78a6-3 -> 1.2.0-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded openmpi (4.0.4-1 -> 4.0.5-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gst-plugins-bad (1.16.2-13 -> 1.18.0-2)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gst-plugins-base (1.16.2-2 -> 1.18.0-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gst-plugins-ugly (1.16.2-4 -> 1.18.0-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gstreamer-vaapi (1.16.2-2 -> 1.18.0-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded gupnp-av (0.12.11+2+gb5ca07c-2 -> 0.12.11+3+g2123c81-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hashable (1.3.0.0-20 -> 1.3.0.0-23)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-primitive (0.7.1.0-13 -> 0.7.1.0-16)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-scientific (0.3.6.2-36 -> 0.3.6.2-39)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-attoparsec (0.13.2.4-19 -> 0.13.2.4-22)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-base-compat-batteries (0.11.1-42 -> 0.11.1-45)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-data-fix (0.3.0-11 -> 0.3.0-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-dlist (1.0-7 -> 1.0-10)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-base-orphans (0.8.2-46 -> 0.8.2-49)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-distributive (0.6.2-19 -> 0.6.2-22)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-comonad (5.0.6-38 -> 5.0.6-41)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-bifunctors (5.5.7-37 -> 5.5.7-42)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-assoc (1.0.2-11 -> 1.0.2-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-these (1.1.1.1-12 -> 1.1.1.1-15)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-strict (0.4-12 -> 0.4-15)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-time-compat (1.9.3-20 -> 1.9.3-23)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-unordered-containers (0.2.12.0-11 -> 0.2.12.0-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-splitmix (0.1.0.1-12 -> 0.1.0.1-15)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-random (1.2.0-12 -> 1.2.0-18)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-uuid-types (1.0.3-42 -> 1.0.3-45)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-vector (0.12.1.2-39 -> 0.12.1.2-42)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-aeson (1.5.4.0-4 -> 1.5.4.0-7)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-aeson-pretty (0.8.8-70 -> 0.8.8-73)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-colour (2.3.5-59 -> 2.3.5-62)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-ansi-terminal (0.10.3-35 -> 0.11-4)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hourglass (0.2.12-66 -> 0.2.12-69)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-memory (0.15.0-33 -> 0.15.0-36)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-asn1-types (0.3.4-21 -> 0.3.4-24)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-asn1-encoding (0.9.6-42 -> 0.9.6-45)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-asn1-parse (0.9.5-42 -> 0.9.5-45)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-async (2.2.2-24 -> 2.2.2-27)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-base64-bytestring (1.2.0.0-7 -> 1.2.0.0-10)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-blaze-markup (0.8.2.7-11 -> 0.8.2.7-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-blaze-html (0.9.1.2-41 -> 0.9.1.2-44)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-case-insensitive (1.2.1.0-23 -> 1.2.1.0-26)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-cmark-gfm (0.2.1-36 -> 0.2.2-2)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-commonmark (0.1.0.2-8 -> 0.1.0.2-11)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-emojis (0.1-31 -> 0.1-34)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-commonmark-extensions (0.2.0.1-8 -> 0.2.0.1-11)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-quickcheck (2.14.1-21 -> 2.14.1-27)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-pandoc-types (1.21-15 -> 1.21-18)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-commonmark-pandoc (0.2.0.0-10 -> 0.2.0.1-1)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-network (3.1.2.0-23 -> 3.1.2.0-29)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-socks (0.6.1-42 -> 0.6.1-45)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-cryptonite (0.27-14 -> 0.27-17)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-pem (0.2.4-98 -> 0.2.4-101)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-x509 (1.7.5-75 -> 1.7.5-78)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-x509-store (1.6.7-74 -> 1.6.7-77)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-x509-validation (1.6.11-74 -> 1.6.11-77)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-tls (1.5.4-29 -> 1.5.4-32)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-x509-system (1.6.6-142 -> 1.6.6-145)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-connection (0.3.1-49 -> 0.3.1-52)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-data-default-instances-dlist (0.0.1-84 -> 0.0.1-87)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-data-default (0.7.1.1-71 -> 0.7.1.1-74)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-doclayout (0.3-29 -> 0.3-32)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hsyaml (0.2.1.0-36 -> 0.2.1.0-39)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-text-conversions (0.3.0-42 -> 0.3.0-45)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-doctemplates (0.8.2-40 -> 0.8.2-43)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-glob (0.10.1-12 -> 0.10.1-15)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-haddock-library (1.9.0-29 -> 1.9.0-32)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hslua (1.1.2-21 -> 1.1.2-24)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-temporary (1.3-92 -> 1.3-97)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hslua-module-system (0.2.2-10 -> 0.2.2-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hslua-module-text (0.2.1-74 -> 0.2.1-77)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-network-uri (2.6.3.0-155 -> 2.6.3.0-160)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-http (4000.3.14-273 -> 4000.3.15-5)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-http-types (0.12.3-78 -> 0.12.3-81)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-streaming-commons (0.2.2.1-11 -> 0.2.2.1-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-http-client (0.7.2.1-17 -> 0.7.2.1-25)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-http-client-tls (0.3.5.3-294 -> 0.3.5.3-299)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-hxt (9.3.1.18-136 -> 9.3.1.18-141)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-ipynb (0.1.0.1-82 -> 0.1.0.1-87)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-jira-wiki-markup (1.3.2-11 -> 1.3.2-14)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-juicypixels (3.3.5-21 -> 3.3.5-24)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-skylighting-core (0.8.5-44 -> 0.8.5-49)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-skylighting (0.8.5-44 -> 0.8.5-49)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-split (0.2.3.4-57 -> 0.2.3.4-63)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-tagsoup (0.14.8-46 -> 0.14.8-49)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-texmath (0.12.0.2-76 -> 0.12.0.3-2)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-unicode-transforms (0.3.7-7 -> 0.3.7-10)
[2020-09-26T17:23:25+0200] [ALPM] upgraded haskell-zip-archive (0.4.1-50 -> 0.4.1-53)
[2020-09-26T17:23:25+0200] [ALPM] upgraded htop (3.0.1-2 -> 3.0.2-1)
[2020-09-26T17:23:26+0200] [ALPM] upgraded hugo (0.74.3-1 -> 0.75.1-1)
[2020-09-26T17:23:26+0200] [ALPM] upgraded libmagick6 (6.9.11.28-1 -> 6.9.11.30-1)
[2020-09-26T17:23:26+0200] [ALPM] upgraded inkscape (1.0-6 -> 1.0.1-1)
[2020-09-26T17:23:26+0200] [ALPM] upgraded lib32-glib2 (2.64.5-1 -> 2.66.0-1)
[2020-09-26T17:23:26+0200] [ALPM] upgraded lib32-systemd (246.4-1 -> 246.6-1)
[2020-09-26T17:23:26+0200] [ALPM] upgraded lib32-libgudev (233-1 -> 234-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-openssl (1:1.1.1.g-1 -> 1:1.1.1.h-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-libldap (2.4.50-1 -> 2.4.53-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-mesa (20.1.7-1 -> 20.1.8-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-nspr (4.28-1 -> 4.29-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-nss (3.56-1 -> 3.57-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-pango (1:1.46.1-1 -> 1:1.46.2-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-vulkan-icd-loader (1.2.151-1 -> 1.2.153-2)
[2020-09-26T17:23:27+0200] [ALPM] upgraded lib32-vulkan-intel (20.1.7-1 -> 20.1.8-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libdazzle (3.36.0-1 -> 3.38.0-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libheif (1.8.0-1 -> 1.9.1-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libmwaw (0.3.16-1 -> 0.3.17-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libspectre (0.2.9-1 -> 0.2.9-2)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libva-mesa-driver (20.1.7-1 -> 20.1.8-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libwebsockets (4.0.21-1 -> 4.1.2-1)
[2020-09-26T17:23:27+0200] [ALPM] upgraded libwpe (1.6.0-1 -> 1.8.0-1)
[2020-09-26T17:23:29+0200] [ALPM] upgraded linux (5.8.8.arch1-1 -> 5.8.10.arch1-1)
[2020-09-26T17:23:33+0200] [ALPM] upgraded linux-headers (5.8.8.arch1-1 -> 5.8.10.arch1-1)
[2020-09-26T17:23:36+0200] [ALPM] upgraded linux-lts (5.4.64-1 -> 5.4.67-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded linux-lts-headers (5.4.64-1 -> 5.4.67-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded mesa-vdpau (20.1.7-1 -> 20.1.8-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded metis (5.1.0.p9-1 -> 5.1.0.p10-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded moreutils (0.63-2 -> 0.64-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded mosquitto (1.6.11-1 -> 1.6.11-2)
[2020-09-26T17:23:43+0200] [ALPM] upgraded noto-fonts-emoji (20200720-1 -> 20200916-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded numactl (2.0.13-3 -> 2.0.14-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded opusfile (0.11-2 -> 0.12-1)
[2020-09-26T17:23:43+0200] [ALPM] upgraded pacman-mirrorlist (20200801-1 -> 20200920-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded pandoc (2.10.1-19 -> 2.10.1-28)
[2020-09-26T17:23:44+0200] [ALPM] upgraded perl-libwww (6.47-1 -> 6.49-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded perl-html-parser (3.73-1 -> 3.74-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded pipewire (0.3.11-1 -> 0.3.12-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded pipewire-pulse (0.3.11-1 -> 0.3.12-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-cffi (1.14.2-1 -> 1.14.3-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-cryptography (3.1-1 -> 3.1.1-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-toml (0.10.1-1 -> 0.10.1-2)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-isort (5.5.2-1 -> 5.5.3-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded qhull (2020.1-1 -> 2020.2-3)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-matplotlib (3.3.1-1 -> 3.3.2-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-pygments (2.6.1-3 -> 2.7.1-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-pylint (2.5.3-2 -> 2.6.0-1)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-pyqt5 (5.15.0-3 -> 5.15.1-2)
[2020-09-26T17:23:44+0200] [ALPM] upgraded python-pyrsistent (0.17.1-1 -> 0.17.3-1)
[2020-09-26T17:23:45+0200] [ALPM] upgraded python-pyusb (1.0.2-4 -> 1.1.0-1)
[2020-09-26T17:23:45+0200] [ALPM] upgraded python-ruamel.yaml.clib (0.2.1-1 -> 0.2.2-1)
[2020-09-26T17:23:45+0200] [ALPM] upgraded python-sip (4.19.24-1 -> 4.19.24-2)
[2020-09-26T17:23:45+0200] [ALPM] upgraded python-zipp (3.1.0-1 -> 3.2.0-1)
[2020-09-26T17:23:45+0200] [ALPM] upgraded radicale (3.0.5-1 -> 3.0.6-1)
[2020-09-26T17:23:45+0200] [ALPM] upgraded sdl2_mixer (2.0.4-4 -> 2.0.4-5)
[2020-09-26T17:23:45+0200] [ALPM] upgraded shellcheck (0.7.1-130 -> 0.7.1-139)
[2020-09-26T17:23:46+0200] [ALPM] upgraded signal-desktop (1.36.1-1 -> 1.36.3-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded snapper (0.8.13-1 -> 0.8.14-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded sonnet (5.73.0-1 -> 5.74.0-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded sox (14.4.2-6 -> 14.4.2-7)
[2020-09-26T17:23:46+0200] [ALPM] upgraded vulkan-intel (20.1.7-1 -> 20.1.8-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded wpebackend-fdo (1.6.1-1 -> 1.8.0-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded webkit2gtk (2.28.4-1 -> 2.30.1-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded steam-native-runtime (1.0.0.62-1 -> 1.0.0.62-2)
[2020-09-26T17:23:46+0200] [ALPM] upgraded sudo (1.9.2-1 -> 1.9.3.p1-1)
[2020-09-26T17:23:46+0200] [ALPM] upgraded systemd-sysvcompat (246.4-1 -> 246.6-1)
[2020-09-26T17:23:47+0200] [ALPM] upgraded teamspeak3 (3.5.3-1 -> 3.5.3-2)
[2020-09-26T17:23:47+0200] [ALPM] upgraded tracker (2.3.5-1 -> 2.3.6-1)
[2020-09-26T17:23:47+0200] [ALPM] upgraded tracker-miners (2.3.4-1 -> 2.3.5-1)
[2020-09-26T17:23:47+0200] [ALPM] upgraded vim-runtime (8.2.1634-1 -> 8.2.1704-1)
[2020-09-26T17:23:47+0200] [ALPM] upgraded vim (8.2.1634-1 -> 8.2.1704-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded vlc (3.0.11.1-2 -> 3.0.11.1-3)
[2020-09-26T17:23:48+0200] [ALPM] upgraded vte-common (0.60.3-1 -> 0.62.0-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded vte3 (0.60.3-1 -> 0.62.0-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded wireshark-cli (3.2.6-1 -> 3.2.7-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded wireshark-qt (3.2.6-1 -> 3.2.7-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded xf86-video-vesa (2.4.0-3 -> 2.5.0-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded xterm (359-1 -> 360-1)
[2020-09-26T17:23:48+0200] [ALPM] upgraded zeromq (4.3.2-3 -> 4.3.3-2)
```

**Comment by jnsh** [comment] 2020-09-26 17:01
Thanks for the report.

This is a duplicate of https://github.com/jnsh/arc-theme/issues/80. Looks like `vte3-0.62.0` is using the recently introduced `@text_view_bg` public color, that I had not implemented yet. A commit that fixes this will be pushed shortly.

Closing as a duplicate.

**Closed by jnsh** 2020-09-26 17:01 UTC
