### ISSUE TITLE
Create versioned releases

### ISSUE THREAD

**Issue by Justinzobel** [jnsh/arc-theme#18] opened 2020-03-16 01:56 UTC
Please create versioned releases as you go so they can be used in distributions instead of relying on a git clone/checkout.

**Comment by Justinzobel** [comment] 2020-03-16 01:57
If you can also maybe take over ownership of the original repository as it's now after a new maintainer. Finding your fork among hundreds of others was not easy.

**Comment by jnsh** [comment] 2020-03-16 02:17
I'm planning on rolling out a release tarball, once I got all the GNOME 3.36 regressions sorted out.

I don't think there's any possibility for taking ownership of the original repo, since the original author hasn't been active for years.

**Comment by fgblomqvist** [comment] 2020-04-08 19:05
I think @Justinzobel meant https://github.com/arc-design/arc-theme as the "original" repo. I know it's not the original, but it is seemingly the official these days (mostly thanks to the name of the org/repo). Looks like whoever maintained that one are still active (I think it might be @fossfreedom and @NicoHood). Might be worth a shot to send them an email to see what they think :)

Just like many others have said, this is an excellent theme and we're all very happy that someone is still maintaining it! I'd be happy to try to get an updated package into the repos for Fedora that would be based on this repo, assuming some of the politics get resolved first (potentially?).

**Comment by jnsh** [comment] 2020-04-08 21:35
@fgblomqvist You might be right. Either way, I think moving the repo at this point would only cause more confusion and additional work, with little benefit. I did attempt working with the `arc-design` admins even before they moved the repo under that project name, but I suppose we just couldn't find solution that worked for everybody. I think they both should be aware of my repo, and if they wanted, they could try to direct people to this repo with e.g. note on the README.

Whether there's a official release or not, if you want Fedora (or any other distribution) to ship a package from this repo, you should open a bug, or notify the Arc-theme packager for you distro some other way. This repo should currently be perfectly suitable for daily use, and I'd imagine most distribution packagers should be able to build a release from a git snapshot somehow. I simply don't want to roll out a "stable" release when there are still a few notable issues.

As a progress report for the stable release: I've had to basically rewrite part of the gnome-shell theme to fix the updated calendar popup on GNOME 3.36, and that has required some thinking. I think I'm pretty close to getting it done, but it might still take a few weeks until I can roll out the new stable version.

**Comment by fgblomqvist** [comment] 2020-04-08 21:59
Alright. Maybe things can be consolidated a bit in the future. Thanks for the explanation.

I'll see what I can do with regards to the package (and try to talk to the maintainer). Certainly won't be hard to build a Fedora package against a git snapshot. Thanks for the progress update on a more stable version, appreciate the work you're putting in.

**Comment by NicoHood** [comment] 2020-04-14 10:35
Hi @jnsh 
Sorry for coming too late into the discussion, I was not much active on Github recently. I think we should discuss the future of the theme once again, as many people (me too) love the theme and wish it can be continued.

I can only speak for myself, but I aint got skills not time to maintain the theme currently. It seems @fossfreedom has similar issues. Currently you are the onlyone providing the theme with updates and patches, and on top you are the only one with good gtk theming skills.

Now my wish is, that we produce as less confusion as possible to the end users and package maintainers. So a constantly switching upstream is what I want to avoid. My suggestion is, that you will become an admin of the arc-design group and maintain the theme with you current codebase from there. That is what I can offer to you.

No matter how you decide, we (package maintainers) require a gpg signed release (or git commit) to package the software secure. We are responsible for many users, so this is an important aspect. So if you decide to go on with the theme in this repository, you can checkout [this guide](https://github.com/NicoHood/gpgit). If you decide to join arc-design I can take over that job as well.

I am happy to assist, if you need further information. Thanks for your effort in the theme :-)

**Comment by jnsh** [comment] 2020-04-15 01:44
@NicoHood I have already been provided with admin permissions to the `arc-design` organization, and given written permission to do whatever I wish.

However, moving my repo to `arc-design` is not possible: The codebases can't be merged, so the old `arc-design/arc-theme` repo would have to be deleted, removing all development history, and references to issues, pull requests etc. Furthermore I think moving the repo at this point would only add more confusion, and cause unnecessary work with very little benefit.

I'm thinking of adding a note to the README of the `arc-design` repo, or something similar to forward people here.

As I've mentioned many times already, a formal (and properly signed) release is planned once I get certain issues sorted out.

**Comment by NicoHood** [comment] 2020-04-19 15:06
> The codebases can't be merged, so the old arc-design/arc-theme repo would have to be deleted, removing all development history, and references to issues, pull requests etc.

I can handle that without loosing the history. We can either create different branches or merge the branch with unrelated histories. I can figure that out, ive done similar things before. If you wish, I would investigate.

> I'm thinking of adding a note to the README of the arc-design repo, or something similar to forward people here.

That is for sure the way to go. I still like the idea of having it at the same upstream. However now its your own decision.

> As I've mentioned many times already, a formal (and properly signed) release is planned once I get certain issues sorted out.

That sounds good to me. :-)

**Comment by chewi** [comment] 2020-05-10 10:33
I've just bumped the Gentoo Linux package with the latest from this repository. Thanks for keeping it alive. I think merging things back into the old project sounds good, however you do it, but I don't really mind.

**Comment by jnsh** [comment] 2020-05-10 14:52
@chewi Thank you for letting me know. I'll add the gentoo package to the list on the README. I'm also trying to roll out the release tarball today, but if the ebuild already builds from 958b9b554cde5a8be7280bdf4a908ebe833cbd81, there won't be any functional changes.

Since this question keeps coming up, I'm giving a clear and definite answer: I have no intention of moving my repo to `arc-design`.

I think I have explained my reasoning in detail for this on above posts, though there may be some additional points that I haven't mentioned here. While @NicoHood's above suggestion of merging my repo as a new branch might work around some technical issues, the two projects are completely separate, and merging them would only confuse things further.

I did suggest taking over the maintainership "officially" even before the `NicoHood/arc-theme` was moved under the `arc-design` project. At that point moving the repo to a community organization would have made sense, but merging to an existing project with existing repo with the same name does not.

Additionally I already have a huge TODO of actual fixes and improvements for this project, and any time spent messing with merging the projects could be used for much more useful things.

To be clear, even if the project is developed under my personal repo, I wouldn't mind some kind of community based development, and I do greatly appreciate any feedback and other contributions. Also I don't mind to giving write permissions if someone wants to work actively on the project, and shows that they are capable of doing so.

If there are any willing contributors, I can add some tasks to the issues list that could use some help, and I'm happy to assist and give advice for them if needed.

**Comment by jnsh** [comment] 2020-05-13 01:04
Released version [20200513](https://github.com/jnsh/arc-theme/releases/tag/20200513).

This was my first time publishing a release, so please let me know if there are any problems or there's anything that could be done better.

**Comment by WhyNotHugo** [comment] 2020-05-13 07:18
Thank you very much for this! I greatly appreciate the huge amount of effort you've put into this!

**Closed** 2020-05-17 21:12 UTC

**Comment by NicoHood** [comment] 2020-05-27 07:29
@jnsh Where can I find your public PGP key? I could not find it on any keyserver, or I was using the wrong server maybe?

**Comment by jnsh** [comment] 2020-05-27 14:22
@NicoHood Great! I'll add the package to the README once you get it to the mirrors.

>- I got an error, that I need to add a cinnamon version. No problem, however it would be nice to have those building details also in the readme? The fork from arc-design has added such information, maybe you can orientate on that.

The build instructions got quite long and complex, so I separated them to [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md). I think this is clearly mentioned in the [README](https://github.com/jnsh/arc-theme#manual-installation). The INSTALL.md should explain the necessary build options etc. in detail. Let me know if you have any suggestions for making it clearer, or other improvements.

>- Where can I find your public PGP key? I could not find it on any keyserver, or I was using the wrong server maybe?

At the time I was setting up the PGP key, the default keyserver (`hkps://hkps.pool.sks-keyservers.net`) seemed to be down so I used `hkps://pgp.mit.edu`. I was under the impression that it would be synced with the default keyserver.

The `hkps://pgp.mit.edu` keyserver seems to be down ATM, but I was able to succesfully send the key to the default keyserver as well this time. Using `gpg --search-keys "Joonas Henriksson"` should work.

Sorry about the confusion. I'm quite new to PGP signing, as I haven't had any need for it before this.

>- I am using cinnamon version 4.6.1, is that correct? I assume that 4.6 is the value to use, but the build script outputs no error.

Passing either `4.6` or `4.6.1` to the `--with-cinnamon=` flag will build the theme from `common/cinnamon/4.6` directory.

>- Is that the correct way to build? I've just added the cinnamon version. Did the dependencies change?

You can compare to the [arc-gtk-theme-jnsh-git](https://aur.archlinux.org/packages/arc-gtk-theme-jnsh-git/) PKGBUILD from AUR. It's maintained by myself so everything should be correct.

A few suggestions for the snip your posted:
- `resvg` and `parallel` aren't required or supported.
- You can omit the `gtk3` from `makedepends` by defining the GTK 3 version manually using the `--with-gtk3=` option. I think this should be helpful if you're building in a clean chroot.

Make sure you bump the gnome-shell and cinnamon (and gtk3) versions to the latest versions available from Arch package mirrors when you update the PKGBUILD. If there are other build related changes, I will mention them on the changelog for every release.

**Comment by NicoHood** [comment] 2020-06-02 10:23
Nice work, thanks for the feedback. The package will be published within the next few minutes.

I suggest merging your aur package with the arc-gtk-theme-git package. Comments will be merged, and you will be a maintainer too. If you are ready for the merge, I can start it.

**Comment by Noeljunior** [comment] 2020-06-02 10:45
@NicoHood I took over the aur package when you dropped it. I did so because I had the intention of merging it with jnsh's. We decided to wait until the community's was be pointed to here, which happened now.
So now jnsh and I are co-maintainers on arc-gtk-theme-git. If you and jnsh agree, you can keep me as co-maintainer as I have interest on this package (as I used it everywhere) and I can help if on packaging if needed. Or, if you prefer to move me out, that's fine too. Just let me know.

**Comment by jnsh** [comment] 2020-06-03 03:18
@NicoHood Nice! Thank you.

I changed the `arc-gtk-theme-git` AUR package to point to this project, and updated the `PKGBUILD` based on the `arc-gtk-theme-jnsh-git` package. There's also an existing [package merge request](https://lists.archlinux.org/pipermail/aur-requests/2020-June/040924.html), waiting for a TU to accept it.

@Noeljunior It's perfectly fine for me if you want to keep co-maintaining the package. The main maintenance chore is to bump the version flags for the `autogen.sh` command, whenever the packages are updated on Arch mirrors. I can keep the `PKGBUILD` up to date with build system changes or anything else that requires bigger changes.

**Comment by NicoHood** [comment] 2020-06-03 07:10
Merge request accepted :-)
