### ISSUE TITLE
Error during building package

### ISSUE THREAD

**Issue by MateuszKubuszok** [jnsh/arc-theme#14] opened 2020-03-08 18:36 UTC
I just updated by Arch Linux to the newest version. Since there were some changes in Gnome that made the community theme package look outdated I started looking for an update and found out that this is the repository that is actively maintained.

When I tried to build AUR package I got this:

```
make[2]: Leaving directory '/var/tmp/pamac-build-dev/arc-gtk-theme-jnsh-git/src/arc-theme/common/gtk-2.0'
Making all in gtk-3.0
make[2]: Entering directory '/var/tmp/pamac-build-dev/arc-gtk-theme-jnsh-git/src/arc-theme/common/gtk-3.0'
Making all in 3.24
make[3]: Entering directory '/var/tmp/pamac-build-dev/arc-gtk-theme-jnsh-git/src/arc-theme/common/gtk-3.0/3.24'
make[3]: *** No rule to make target 'all'.  Stop.
make[3]: Leaving directory '/var/tmp/pamac-build-dev/arc-gtk-theme-jnsh-git/src/arc-theme/common/gtk-3.0/3.24'
make[2]: *** [Makefile:456: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/pamac-build-dev/arc-gtk-theme-jnsh-git/src/arc-theme/common/gtk-3.0'
make[1]: *** [Makefile:465: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/pamac-build-dev/arc-gtk-theme-jnsh-git/src/arc-theme/common'
make: *** [Makefile:363: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

AUR points at the newest master. Is there some more information I could provide to help resolve that issue?

**Comment by jnsh** [comment] 2020-03-08 19:07
Thank you for the report.

I can reproduce the build issue when building the AUR package. Oddly enough, there are no errors when building manually from the source, which is why I didn't notice this myself earlier.

I'll try to figure out the cause, and either push a fix or update the PKGBUILD, asap.

As a side note, I didn't expect GNOME 3.36 to roll out in Arch repos this early (since the official release date is March 11th), and haven't updated the GNOME Shell theme for the new version yet. I'm currently working on it and can hopefully push fixes for most annoying issues in the next few days.

Until then, don't be alarmed that the GNOME Shell theme has a number of visual issues on 3.36. :)

**Comment by jnsh** [comment] 2020-03-08 19:23
This should be fixed with https://github.com/jnsh/arc-theme/commit/c1f2175a5d9d076d5bcf8e346cbdc608d3fb4ee6.

Thanks again for the report.

**Closed by jnsh** 2020-03-08 19:23 UTC
