### ISSUE TITLE
 Application icons too large with 200% scale

### ISSUE THREAD

**Issue by dieggsy** [jnsh/arc-theme#156] opened 2021-09-23 20:11 UTC
Reposting here since the original repo is unmaintained:

I'm using Gnome 40 on Fedora 34. I have a 2560x1440 screen with 200% scaling set. Below is a comparison at the same scale level (200%) between the default shell theme vs arc shell themes. This weirdly seems to happen the second time I access the applications and every time after, but not the first after switching the theme.

Default:
![Screenshot from 2021-09-23 15-37-10](https://user-images.githubusercontent.com/9020453/134572936-605190fe-98f0-4f44-b873-428e956a461a.png)

Arc:
![Screenshot from 2021-09-23 15-37-30](https://user-images.githubusercontent.com/9020453/134572970-cccf64b1-fc1b-4b65-b468-a54c1a08936e.png)

**Comment by jnsh** [comment] 2021-09-24 01:21
Thank you for the report.
Does this happen with all your shell extensions (apart from user-theme) disabled?

**Comment by dieggsy** [comment] 2021-09-24 01:32
@jnsh I turned off all other extensions and theming (besides the Arc shell theme), and it does still seem to happen.

**Comment by jnsh** [comment] 2021-09-24 01:38
Ok, thank you for testing.

I know gnome-shell scales the icons automatically according to available space, so it could be that paddings for the icon grid are just different in Arc. However, it seems odd that the icons seem to be overlapping each other slightly, so this could be something not that obvious as well.

I'll investigate this at some point, but unfortunately at the moment I'm rather busy to get the GTK4 port finalized.

**Comment by dieggsy** [comment] 2021-09-24 01:42
@jnsh Right. It's odd that on first entry it doesn't seem to happen. And no worries - please let me know if there's anything else I can do to help, Otherwise, I'm a patient guy (and I don't use the applications view a whole lot). Thanks a lot for you work on the theme!

**Comment by dieggsy** [comment] 2021-09-24 13:05
I was testing this and on quickly opening and closing this view over and over, the icons are sometimes too large, sometimes the right size.

**Comment by dieggsy** [comment] 2021-09-24 14:03
One more thing: this is also wih .80 font scaling in gnome-tweaks, but changing that to 1.0 seemed to have no effecte either

**Comment by dieggsy** [comment] 2021-10-10 22:47
Thanks for following up and for opening that issue. Weirdly, I haven't been able to reproduce this in the default theme.

**Comment by jnsh** [comment] 2022-01-04 01:07
I had left this open in case I could think of something to this, but without being able to reproduce your exact issue, there's nothing I can do. Looks like the similar issue I described on my previous response doesn't happen in gnome-shell 41 either.

Also seeing there's [another upstream bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4768) about oversized grid icons, I'm even more confident that this is caused by something in gnome-shell, rather than something being off with the theme.

@dieggsy If you are still experiencing this issue, I hope it gets sorted somehow. If you're confident editing the theme .scss file, you could try adjusting paddings and other sizing in the grid. If you find something that helps, I may be able to apply it to the theme as a fix.

Closing for now. Feel free to continue discussion, if there's anything.

**Closed by jnsh** 2022-01-04 01:07 UTC
