### ISSUE TITLE
Shell Theme: GNOME Overview won't zoom out enough (GNOME 40)

### ISSUE THREAD

**Issue by ljrk0** [jnsh/arc-theme#125] opened 2021-04-18 18:34 UTC
### Before submitting

- [x] Ensure that the issue is present with the latest Arc-theme release, or latest git snapshot.
- [x] Test whether the issue also appears with default themes (e.g. Adwaita for GTK and GNOME).
- [x] Make sure you have built the correct theme versions for GTK 3, GNOME Shell and Cinnamon themes.
- [x] Make sure the issue persists between restarts.
- [x] For GTK 3 related issues, try clearing your user's `~/.config/gtk-3.0/gtk.css`, if it exists.

### Details

When using the Arc Shell theme and many windows open, the overview often stops "zooming out" to show all windows next to each other, c.f. the following screen shots done with Adwaita/Default v. Arc

![image](https://user-images.githubusercontent.com/7831843/115156567-177b8e80-a085-11eb-9a9b-6f7044d5ad01.png)
![Screenshot from 2021-04-18 20-31-59](https://user-images.githubusercontent.com/7831843/115159480-95469680-a093-11eb-9c47-4a439c5d20b5.png)

(I did try restarting the GNOME Shell after changing to Arc, despite these screenshots being taken in the same session.)

Also, as long as the zoom-out is in the broken state, typing in order to search is broken:

![image](https://user-images.githubusercontent.com/7831843/115156435-93c1a200-a084-11eb-9794-e334f30c0423.png)

Ironically, taking a screenshot fixes the problem by forcing a re-paint/refresh of the scene(?).  Thus, just after the screenshot was taken, the "zooming process" is unfrozen (or the search results are correctly displayed):

![image](https://user-images.githubusercontent.com/7831843/115156583-282c0480-a085-11eb-930f-30db817d78b1.png)

- **Distribution and version**: Arch Linux, rolling + rolling with [testing]
- **Versions for the affected applications/desktops/tookits** GNOME 40
- **Installation method (package or compiled manually)** Arch User Repository, -git package
- **Arc-theme version**  20210412.r0.g3d63e639-1

**Comment by jnsh** [comment] 2021-04-18 20:00
> When using the Arc Shell theme and many windows open, the overview often stops "zooming out" to show all windows next to each other, c.f. the following screen shots done with Adwaita/Default v. Arc
> 
> ![image](https://user-images.githubusercontent.com/7831843/115156567-177b8e80-a085-11eb-9a9b-6f7044d5ad01.png)
> ![image](https://user-images.githubusercontent.com/7831843/115156576-22362380-a085-11eb-970f-33c17170cde3.png)

I think you posted the same screenshot twice. I haven't experienced anything similar to what you described myself, so I'm not 100% sure what's happening. 

Also, the way the windows are arranged in overview doesn't look normal in your not-bugged screenshots. Are you by any chance using some extension that changes this? If so, can you test whether the problem persists with that extension disabled (and/or with all your extensions disabled, for good measure).

**Comment by ljrk0** [comment] 2021-04-18 20:19
Oh, I switched out the screenshots because of personal identifying information of others but missed that -- I fixed that.

I totally forgot about the extensions as I didn't consciously enable them, but I fumbled around with a custom package which enabled them on install (and didn't deactivate on removal).  Indeed, after deactivating "native window placement" this does not occur anymore, so that's where the incompatibility seems to lie.

The issue definitely didn't occur before GNOME 40, but unfortunately my memory is a little hazy whether that was also the time "native window placement" could have been enabled.

Either way, "for me" the issue is fixed as I don't need the extension, thank you very much for that!  I'm not sure though where the root cause dies.

**Comment by jnsh** [comment] 2021-04-18 20:38
Thanks for testing. At least this revealed the root cause of the issue, although it seems odd that this would only happen with Arc, and not with Adwaita...

Is this upstream issue for native window placement extension identical to what you're experiencing? https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/309

**Comment by ljrk0** [comment] 2021-04-18 20:51
Yep, I only discovered this being kindof-ish related to the theme since I temporarily switched back to Adwaita before the first GNOME 40 compatible release a few days ago and when I switched back this broke.

I definitely see that it isn't smooth as described in the issues you linked, however, with Arc it's worse in that the animation won't play completely but stops before the "zoom out process" is finished.  I suspect it's at least related and hope that a fix for those issues would fix this one as well.  

Annoyingly, after deactivating and re-activating native window placement I cannot reproduce the issue on my laptop anymore (my desktop still has it) ...

Thanks for the links, this helps a great deal (and for maintaining this awesome theme!)

**Comment by jnsh** [comment] 2021-04-18 20:57
Indeed, it seems that the native window placement extension is very broken with GNOME 40 at the moment, so I think this can be considered an upstream bug.

FWIW, I wasn't able to reproduce this after activating the extension, so maybe re-activating it somehow fixes this.

If there are remaining problems after the upstream issues are fixed, and that aren't present with Adwaita, I'll look at resolving them.

Thank you for letting me know about this nevertheless :)

**Closed by jnsh** 2021-04-18 20:57 UTC
