### ISSUE TITLE
Weird behavior with Dash to Dock

### ISSUE THREAD

**Issue by mhdahmad** [jnsh/arc-theme#64] opened 2020-07-28 01:23 UTC
When setting dash to dock extension's option [Panel mode: extend to the screen edge] the following happens:

![Peek 2020-07-28 04-17](https://user-images.githubusercontent.com/63624112/88608198-d4f2cb80-d089-11ea-9307-2ceb8221f0b6.gif)

also you can't slide applications down at all.
Already test it with Adwaita, no problem there.

**Comment by jnsh** [comment] 2020-07-28 01:32
Can you clarify what exactly is happening in the screen capture?

I notice the [ Frequent | All ] buttons shaking. However I can't reproduce this, or being unable to scroll the application grid on my system. Either way, there shouldn't be any way such issues shouldn't result from the custom shell theme, nor there should be anything I could do about them, even if I could reproduce the problem.

Are you using latest version of the theme from this repo, and tested with latest dash to dock from git?

**Comment by mhdahmad** [comment] 2020-07-28 01:43
Apologies about less of issue information.
the problem is with the [ Frequent | All ] buttons shaking. The version used is built from 20200513 version using fedora copr, and dash to dock is from fedora repository also.

I will try build both from the source.

**Comment by jnsh** [comment] 2020-08-13 10:26
Closing this with the assumption that the issue was somehow resolved, since there hasn't been any additional comments. Let me know if this wasn't the case.

**Closed by jnsh** 2020-08-13 10:26 UTC
