### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by rilysh** [jnsh/arc-theme#201] opened 2022-10-30 15:03 UTC
Hi, it's not strictly an issue with Arc theme, but I'd like to know if you folks have any plans to make a new release on GitHub. The last [release](https://github.com/jnsh/arc-theme/releases/tag/20220405) was in April, since then a couple of changes have been done. It'd be nice if a new release has been done here. Some Linux distros rely on the package release version, so they're likely stuck in that April release (for ex. In Void Linux). 

Thanks for maintaining this project so long!
Cheers!

**Comment by jnsh** [comment] 2022-10-30 23:50
I will roll out a new release once I've been able to update the theme for GNOME 43. Unfortunately it's not available for my distribution just yet, and I haven't had time to compile it myself, or set a testing environment some other way.

**Comment by xuanruiqi** [comment] 2022-11-01 16:52
Apparently Arch just rolled out GNOME 43, so there goes testing environment! :-)
Indeed there are some settings that need to be tweaked, since the top right menu layout has been changed

**Comment by jnsh** [comment] 2022-11-02 00:12
Indeed, I now have GNOME 43 installed, will start working on updating the theme when I get a chance. However, I'm rather busy with other things at the moment, so it might be awhile until that happens..

**Comment by xuanruiqi** [comment] 2022-11-10 20:40
No hurry, but apparently one thing that should be a quick fix would be the color of the new power menu (and the new buttons) :-D
Thanks a lot for your work though!
![Screenshot from 2022-11-11 05-38-57](https://user-images.githubusercontent.com/14145609/201201162-0bac2e0a-3d2c-40a5-9f38-c95210128fb4.png)

**Comment by prurigro** [comment] 2022-11-11 20:53
If anyone's looking for a holdover until the actual theme gets updated, I used pieces of this theme, pieces of the one that ships with gnome-shell and did some digging for some remaining unthemed elements to create something that should match the arc aesthetic, at least colour-wise. It can be used by extracting the contents to ~/.themes/

@jnsh You might find it useful to look at this for the few elements that the official theme forgot to include (I guess they didn't notice because the elements defaulted to appropriate colours). There were a couple and I can't remember them all, but `.icon-button` was a big one.

[Blue-Panel.zip](https://github.com/jnsh/arc-theme/files/9993159/Blue-Panel.zip)

**Comment by jnsh** [comment] 2022-12-11 00:56
Finally pushed updates for gnome-shell 43 and cinnamon 5.4. Apologies for the long delay.

The new gnome shell quick menu could do some final padding tweaks, but otherwise everything should be in order. However I appreciate if anyone can do some testing, and report back if you notice anything that looks off.

I'll release a new version some time next week, if everything seems ok.

One thing to point out about GNOME 43, is that due to libadwaita oddities, some applications (e.g. Nautilus) will look broken, and currently there is nothing that can be done to fix this in the theme.

**Comment by xuanruiqi** [comment] 2022-12-14 03:30
Yeah, the margins need to be a bit wider. Otherwise most things look fine.
There seems to be no option to change the color of the power sub-menu, though.

**Comment by xuanruiqi** [comment] 2022-12-14 09:16
I mean the color of the sub-menu itself. As I have observed, it always appears in black.
However, as it seems to appear exactly the the same in all themes, it's likely not configurable.

**Comment by jnsh** [comment] 2022-12-14 18:07
@xuanruiqi With the updated theme from `master`, and with Arc (light) variant, the sub menu should appear with light background. Nothing like the screenshot you posted earlier.

**Comment by xuanruiqi** [comment] 2022-12-15 04:40
Never mind, I forgot to bump GNOME Shell version when building.
Indeed it looks much better now! But I wonder if the edges of the submenu could be made a bit rounder, so as to provide a more unified feel.

**Comment by jnsh** [comment] 2022-12-17 07:43
@xuanruiqi The current rounder button corners are derived from Adwaita based default theme, where they are common. Arc however uses smaller ~3px rounded corners all around, similar to the submenus in current git master.

As I've done some further small adjustments to the quick menu theming, I've been considering switching the menu buttons to use the smaller Arc based corner rounding as well:

![Untitled](https://user-images.githubusercontent.com/39574454/208231227-16f1f42d-2d3b-49e7-88ef-49714b970290.png) ![Untitled2](https://user-images.githubusercontent.com/39574454/208231228-41c76cf3-ac40-4f2b-8ae9-05de7419bc61.png)

There's still some other fine tweaking I'm hoping to get done, if they don't turn out to be complicated.

**Comment by xuanruiqi** [comment] 2022-12-17 07:44
Thanks! That makes a lot of sense to me.

**Comment by jnsh** [comment] 2022-12-18 19:06
[20221218](https://github.com/jnsh/arc-theme/releases/tag/20221218) released, closing.

**Closed by jnsh** 2022-12-18 19:06 UTC

**Comment by NicoHood** [comment] 2022-12-21 17:58
Hey there!
I've updated the theme for the archlinux users. Thanks for doing such a fast update :)

I know that nautilus is broken and you already mentioned it. So there is really no way to fix that?

I also noticed that in the gnome tweaks tool it now says "legacy" applications, does gnome now change to a whole new design pattern? Do you know more about that, I am curios.
![image](https://user-images.githubusercontent.com/6888294/208972586-2f9c2c1e-2235-48d1-8a18-7dd1fc80e03a.png)

**Comment by jnsh** [comment] 2022-12-21 18:11
> Hey there! I've updated the theme for the archlinux users. Thanks for doing such a fast update :)

Nice! The update from my part was anything but fast though unfortunately

> I know that nautilus is broken and you already mentioned it. So there is really no way to fix that?

Not currently. However I'm thinking this _could_ be due to a libadwaita bug.

libadwaita applications can't technically be themed, but the default theme can be overridden at least with the GTK_THEME environment variable. The issue is that if libadwaita application provides its own stylesheets (like e.g. nautilus does), they seem to override any injected debug stylesheets (be it via GTK inspector of GTK_THEME variable), but I haven't had time to investigate further whether this is intended behavior or not.

> I also noticed that in the gnome tweaks tool it now says "legacy" applications, does gnome now change to a whole new design pattern? Do you know more about that, I am curios.

Yes, in short they use libadwaita now. You can look up more on that.

**Comment by pweisenburger** [comment] 2023-04-01 18:05
> The issue is that if libadwaita application provides its own stylesheets (like e.g. nautilus does), they seem to override any injected debug stylesheets (be it via GTK inspector of GTK_THEME variable), but I haven't had time to investigate further whether this is intended behavior or not.

Hi, there may be a way to make those applications use a custom stylesheet:
https://www.reddit.com/r/gnome/comments/v1aw6k/themeing_libadwaita_a_tldr/
https://github.com/odziom91/libadwaita-theme-changer

Essentially, one can copy or symlink the theme's `gtk.css`, `gtk-dark.css` and `assets` to `$HOME/.config/gtk-4.0`.

In a quick test, I was able to change the style of Nautilus 43's sidebar and list view just by quick-and-dirty adding the following lines to the `gtk-dark.css` file, which brings the look of the list view mode somewhat closer to the Arc theme:
```css
.nautilus-window, .nautilus-window placessidebar list { background-color: transparent; }
.nautilus-window placessidebar { background-color: rgba(51, 51, 51, 0.95); }
.nautilus-window listview { padding: 0 }
.nautilus-window listview row { margin: 0; border-radius: 0; }
.nautilus-window listview row:selected { background-color: #5294e2; }
.nautilus-window listview row cell { padding: 0; }
```

This makes me think that there is a way to apply the theme with the right setup.

For the test, I also had the `GTK_THEME` environment variable set accordingly. Note that I used "unpacked" CSS files and assets. I couldn't get this work when the files where inside `gtk.gresource`.

As a side note: For Arch users, this patched version of libadwaita might be interesting: https://aur.archlinux.org/packages/libadwaita-without-adwaita-git

**Comment by jnsh** [comment] 2023-04-01 19:42
> In a quick test, I was able to change the style of Nautilus 43's sidebar and list view just by quick-and-dirty adding the following lines to the `gtk-dark.css` file, which brings the look of the list view mode somewhat closer to the Arc theme:
> 
> ```css
> .nautilus-window, .nautilus-window placessidebar list { background-color: transparent; }
> .nautilus-window placessidebar { background-color: rgba(51, 51, 51, 0.95); }
> .nautilus-window listview { padding: 0 }
> .nautilus-window listview row { margin: 0; border-radius: 0; }
> .nautilus-window listview row:selected { background-color: #5294e2; }
> .nautilus-window listview row cell { padding: 0; }
> ```

I don't think any of those are in [Nautilus' own stylesheet](https://gitlab.gnome.org/GNOME/nautilus/-/blob/master/src/resources/style.css), which is the thing that overrides any injected stylesheets as I mentioned above. Therefore they should work. Something like `#NautilusPathBar { background-color: red; }` shouldn't work as it'd be overridden by Nautilus' style.css.

Theming libadwaita widgets is definitely possible, and Arc provides styling for those )although it has not been updated to latest version, and I'm not sure whether I'll ever update it or not). It's just that the old style theme selection won't work with libadwaita applications. Copying the theme CSS to the gtk.css is certainly one way to force custom themes.

Some specific libadwaita applications overriding the custom theme with their own CSS is a separate issue that has no workaround that I know of.

**Comment by pweisenburger** [comment] 2023-04-01 20:48
> I don't think any of those are in [Nautilus' own stylesheet](https://gitlab.gnome.org/GNOME/nautilus/-/blob/master/src/resources/style.css)

Some of them are, like the [`border-radius`](https://gitlab.gnome.org/GNOME/nautilus/-/blob/master/src/resources/style.css#L180) of `.nautilus-window listview row` in the example (the selector in the Nautilus stylesheet is different but refers to the same element).

> Something like #NautilusPathBar { background-color: red; } shouldn't work as it'd be overridden by Nautilus' style.css.

I think it does work. Adding this to the stylesheet makes the path bar red (given that the stylesheet is accessible in `$HOME/.config/gtk-4.0`).

**Comment by jnsh** [comment] 2023-04-01 21:05
> > Something like #NautilusPathBar { background-color: red; } shouldn't work as it'd be overridden by Nautilus' style.css.
> 
> I think it does work. Adding this to the stylesheet makes the path bar red (given that the stylesheet is accessible in `$HOME/.config/gtk-4.0`).

Oh it seems to work indeed! I'm quite certain I tested gtk.css before, so either my memory is failing, or this has been fixed in libadwaita. I'll investigate more at some point.

**Comment by pweisenburger** [comment] 2023-04-01 21:21
Cool, thanks! It would be great if the theme supported those applications :-)

**Comment by edricus** [comment] 2023-05-18 13:26
Did you look at Vinceliuice work on libadwaita ?  
It seem he was able to patch libadwaita to be able to integrate his themes.  
You can see his work on it with Qogir : [https://github.com/vinceliuice/Qogir-theme](https://github.com/vinceliuice/Qogir-theme)  
It could be promising if you still plan to work with native apps.

**Comment by jnsh** [comment] 2023-05-18 14:14
> Did you look at Vinceliuice work on libadwaita ? It seem he was able to patch libadwaita to be able to integrate his themes. You can see his work on it with Qogir : https://github.com/vinceliuice/Qogir-theme It could be promising if you still plan to work with native apps.

There are no patching of libadwaita to be more accurate (unless I missed something), although I've seen a patch for libadwaita that would make it not necessary to use the GTK_THEME env variable.

The Qogir install script has an option to link the theme directory to user's $HOME/.config/gtk-4.0, which should allow the libadwaita theming to work correctly, as mentioned in above messages. The Arc-Theme build system is rather different however, and linking in user directories is not really possible with it. However users themselves can apply the linking trick themselves.

Furthermore, I must admit that I don't have much time to work on this project currently, and really don't have the time to work on improved libadwaita support. I'm happy to assist however, if anyone happens to have interest in contributing on this.
