### ISSUE TITLE
App Center on Elementary OS and Pop Os Category Colors

### ISSUE THREAD

**Issue by morgenman** [jnsh/arc-theme#83] opened 2020-09-30 14:33 UTC
Running the latest build on Pop OS and my app center looks like this:
![image](https://user-images.githubusercontent.com/3505950/94699185-0a28cd80-0308-11eb-973e-166e530f5537.png)
Other themes like Matcha handle elementary's App Center colors (Granite I think). 
It would be really great if this could be fixed! 
Also, do you have a ppa for this branch, so we can get updates automatically?

**Comment by jnsh** [comment] 2020-09-30 15:58
This is an [upstream issue](https://github.com/pop-os/shop/issues/124) in Pop!_Shop that has been [reported before](https://github.com/jnsh/arc-theme/issues/67), and won't be fixed in the theme. There's also a recent [issue](https://github.com/pop-os/shop/issues/215) about this (that you have commented on yourself), that mentions a fix that hasn't been merged to Pop!_Shop yet.

If the problem is fixed for every other theme (including Adwaita), but Arc is still broken, let me know and I'll have a look. As long as the default GTK theme also has this problem, this is an upstream bug.

> Also, do you have a ppa for this branch, so we can get updates automatically?

I'm not providing any pre-built packages, and likely never will, especially for distributions that I'm not using myself.

Closing this as upstream bug/duplicate.

**Closed by jnsh** 2020-09-30 15:58 UTC

**Comment by jnsh** [comment] 2020-10-01 03:15
There's also an possible workaround that I didn't think of earlier, until the applications are fixed:

You _should_ be able to fix this locally by adding the necessary color definitions in your users' `~/.config/gtk-3.0/gtk.css` file. I'm unable to confirm whether this works myself, so I'd be interested to hear the results if anyone tries this.

Here's the list of colors from elementary theme, compiled from https://github.com/elementary/stylesheet/blob/master/src/_palette.scss:
```
@define-color STRAWBERRY_100 #ff8c82;
@define-color STRAWBERRY_300 #ed5353;
@define-color STRAWBERRY_500 #c6262e;
@define-color STRAWBERRY_700 #a10705;
@define-color STRAWBERRY_900 #7a0000;
@define-color ORANGE_100 #ffc27d;
@define-color ORANGE_300 #ffa154;
@define-color ORANGE_500 #f37329;
@define-color ORANGE_700 #cc3b02;
@define-color ORANGE_900 #a62100;
@define-color BANANA_100 #fff394;
@define-color BANANA_300 #ffe16b;
@define-color BANANA_500 #f9c440;
@define-color BANANA_700 #d48e15;
@define-color BANANA_900 #ad5f00;
@define-color LIME_100 #d1ff82;
@define-color LIME_300 #9bdb4d;
@define-color LIME_500 #68b723;
@define-color LIME_700 #3a9104;
@define-color LIME_900 #206b00;
@define-color MINT_100 #89ffdd;
@define-color MINT_300 #43d6b5;
@define-color MINT_500 #28bca3;
@define-color MINT_700 #0e9a83;
@define-color MINT_900 #007367;
@define-color BLUEBERRY_100 #8cd5ff;
@define-color BLUEBERRY_300 #64baff;
@define-color BLUEBERRY_500 #3689e6;
@define-color BLUEBERRY_700 #0d52bf;
@define-color BLUEBERRY_900 #002e99;
@define-color BUBBLEGUM_100 #fe9ab8;
@define-color BUBBLEGUM_300 #f4679d;
@define-color BUBBLEGUM_500 #de3e80;
@define-color BUBBLEGUM_700 #bc245d;
@define-color BUBBLEGUM_900 #910e38;
@define-color GRAPE_100 #e4c6fa;
@define-color GRAPE_300 #cd9ef7;
@define-color GRAPE_500 #a56de2;
@define-color GRAPE_700 #7239b3;
@define-color GRAPE_900 #452981;
@define-color COCOA_100 #a3907c;
@define-color COCOA_300 #8a715e;
@define-color COCOA_500 #715344;
@define-color COCOA_700 #57392d;
@define-color COCOA_900 #3d211b;
@define-color SILVER_100 #fafafa;
@define-color SILVER_300 #d4d4d4;
@define-color SILVER_500 #abacae;
@define-color SILVER_700 #7e8087;
@define-color SILVER_900 #555761;
@define-color SLATE_100 #95a3ab;
@define-color SLATE_300 #667885;
@define-color SLATE_500 #485a6c;
@define-color SLATE_700 #273445;
@define-color SLATE_900 #0e141f;
@define-color BLACK_100 #666;
@define-color BLACK_300 #4d4d4d;
@define-color BLACK_500 #333;
@define-color BLACK_700 #1a1a1a;
@define-color BLACK_900 #000;
```

**Comment by morgenman** [comment] 2020-10-01 09:12
Doesn't look like this worked, maybe because I didn't have a gtk.css file there originally.

**Comment by morgenman** [comment] 2020-10-01 09:20
I take that back, after a log out and log in, here we go!
![image](https://user-images.githubusercontent.com/3505950/94791555-d0a69f80-03a5-11eb-872a-c949e1deba8a.png)
Thank you!

**Comment by jnsh** [comment] 2020-10-01 09:27
Thanks for testing. Happy to hear this worked.

Generally restarting the application should be enough to get the `gtk.css` rules applied, but the app center could be running in the background, requiring e.g. killing the background process manually, or logging out in order to have it restarted.
