### ISSUE TITLE
Some dialog doesn't show a close button

### ISSUE THREAD

**Issue by Krafting** [jnsh/arc-theme#22] opened 2020-03-23 06:51 UTC
Distribution and version: Linux Mint Cinnamon 19.3
Version of the arc-theme: Downloaded and compiled few minutes before posting this.

Some windows doesn't show a close button on cinnamon (the font is also a bit smaller), see the attached screenshots with the dialog "Downloading Package information".
It show the close button with the default themes "Mint-Y" and "Mint-X")

Arc Theme:
![arc](https://user-images.githubusercontent.com/36538123/77289597-92d00c80-6cda-11ea-87b2-9d92ea3a03f0.png)
Mint-Y-Dark:
![mint-y-dark](https://user-images.githubusercontent.com/36538123/77289598-9368a300-6cda-11ea-9365-2dcd79645efd.png)
Mint-X:
![mint-x](https://user-images.githubusercontent.com/36538123/77289600-94013980-6cda-11ea-83bb-afd6f35d72b6.png)

It seems that it is affected by the "Window border" customization. (Icon packs doesn't change a thing if you ask)

**Comment by jnsh** [comment] 2020-03-24 03:10
Thank you for the report.

I _think_ all dialog windows should have some sort of dedicated button for closing, just like the download dialog here has a 'Cancel' button. Have you noticed any dialogs where this isn't the case?

My guess is that the dialog titlebar close button has been originally hidden intentionally (as it shouldn't be needed), and I wouldn't like to change this unless there's a good reason.

On the other hand, there could be good reason why the close button isn't hidden on Mint-Y and Mint-X. I'm quite unfamiliar with the metacity theme tbh. If there's anyone more familiar with the cinnamon theming who could shed some more light to this, I'd be very grateful.

If there are any cases where this results in actual functionality/usability issues, this should definitely be fixed. Otherwise I'd have to investigate this more thoroughly when I have resolved all the more important tasks on my TODO.

The inconsistent font size compared to other titlebars, is certainly something that would be nice to get fixed, but this isn't currently one of the most urgent issues either.

**Comment by Krafting** [comment] 2020-03-24 03:24
Well I think it's more of a consistency thing, because It's not consistent to have to go to the right hand corner sometime to close and sometime to the bottom right corner, Also I noticed lots of GTK About dialog doesn't have this close button, but some do, so it is not consistent: 

![image](https://user-images.githubusercontent.com/36538123/77384853-bbaddb80-6d86-11ea-96c8-b3b61c0745ea.png)
![image](https://user-images.githubusercontent.com/36538123/77384903-e730c600-6d86-11ea-9302-48b0f476f90b.png)

Also, I feel like the font is determined by the size of the top bar, and so it is higher when the close icon is there.

Also, I understand that 2 close button isn't needed but I'm sure you see my point too :)

I understand that this isn't a big issue, and if you need a tester to try a fix I'm all yours.
And I'd like to thank you for your work because the theme is much better now, especially on cinnamon!

**Comment by jnsh** [comment] 2020-03-24 03:48
Thanks for pointing out the inconsistency between different dialogs. Looks like this would be worth fixing then. I'll look at it when I have time.

I appreciate the offer for help. Testing isn't generally an issue, since I have a bunch of VMs ready for this purpose. For this issue, the problem is that I'm very unfamiliar with the metacity theming, so even a small fix like this requires quite a bit of investigation.

I'm very grateful for PR, if anyone can figure out the proper fix for this.

**Comment by Krafting** [comment] 2020-03-24 04:05
I did my research, here is what I found for the moment:
It has to do with the lasts lines of the metacity xml: 
On Mint-Y:

**Comment by jnsh** [comment] 2020-03-24 05:27
Thanks, that actually helped. I had a quick look and I think I got a grasp of how the theming works. Easiest way to fix this would be simply changing the dialog style_sets to use use the `normal_style_set`, exactly as you suggested (although the unnecessary style_set and geomerty definitions should be cleaned up as well).

This was done for Mint-Y in https://github.com/linuxmint/mint-y-theme/commit/136abcabe9bb66364fca57538b12a153377b6c65, but unfortunately there are no further reasoning, or references to any discussions.

However, there are other possibilities, e.g. the title bar could be completely hidden for modal dialogs (i.e. the ones that currently don't have close buttons), which I think would be the intended upstream GTK3 design. I'm currently re-thinking the modal dialog titlebar design due to https://github.com/jnsh/arc-theme/issues/20 anyway, and I'd like to keep the design consistent between different DEs.

It might be worth applying the Mint-Y style fix for this first, but again, this isn't highest priority for me right now, as there are a few more severe issues.

> But as I feel it, it wouldn't be a viable solution since this is used across all DE if I'm not wrong ?

I'm not fully sure what you meant by this, but if you're concerned that changing the metacity theme to address this issue in cinnamon, could cause regressions on other DEs that use metacity as the WM, I don't think there should be any risk. If the issue exists on cinnamon, it effects any other desktop that uses metacity as well.

**Comment by Krafting** [comment] 2020-03-24 05:38
For my personal need I changed this and it work perfectly for my need.

> However, there are other possibilities, e.g. the title bar could be completely hidden for modal dialogs (i.e. the ones that currently don't have close buttons), which I think would be the intended upstream GTK3 design. I'm currently re-thinking the modal dialog titlebar design due to #20 anyway, and I'd like to keep the design consistent between different DEs.

The problem would be that we won't be able to move the windows if we completely hide the titlebar (at least for modals on cinnamon)

> I'm not fully sure what you meant by this, but if you're concerned that changing the metacity theme to address this issue in cinnamon, could cause regressions on other DEs that use metacity as the WM, I don't think there should be any risk. If the issue exists on cinnamon, it effects any other desktop that uses metacity as well.

As for this, I just thought that all DE used metacity because I wasn't sure what metacity was exactly but I did my research and yeah, this sentence I said is useless ahah!

I'll keep looking forward to any fixes you do to this theme!

**Closed** 2020-08-04 03:05 UTC
