### ISSUE TITLE
Ubuntu 20.04 arc theme dark yields to white calendar in gnome shell

### ISSUE THREAD

**Issue by muawijhe** [jnsh/arc-theme#95] opened 2020-10-27 14:13 UTC
As the title introduced,
once ll the settings are filled in from gnome-tweaks, the gnome-shell becomes dark but not the calendar.

**Comment by jnsh** [comment] 2020-10-27 14:39
First, please ensure that the Arc gnome-shell theme is built for the gnome-shell version available on your distribution, by passing the version to the `--with-gnome-shell=` build option, as explained in [INSTALL.md](https://github.com/jnsh/arc-theme/blob/master/INSTALL.md).

If you're sure the theme is built for correct version, but the problem still persists, please post a screenshot of the issue.

**Comment by muawijhe** [comment] 2020-10-27 16:57
I installed from Ubuntu 20.04 official package. No build done.

**Comment by jnsh** [comment] 2020-10-27 17:23
The ubuntu 20.04 package is outdated, and not even built from this repository. If you're having problems with it, you should report to the maintainers of the ubuntu package. The problem is most likely fixed with latest version from this repo, when built for correct shell version.

I'm considering this a downstream packaging issue, unless you can reproduce the problem after building the latest release yourself.

AFAIK debian packages should work on ubuntu as well, as long as they are built from matching gnome-shell, gtk3, and cinnamon versions on your current ubuntu installation.

**Comment by muawijhe** [comment] 2020-10-27 19:37
Ok thanks for the feedback.
Perhaps you also should suggest your repo to the ubuntu maintainer, giving
more scope to your beautiful theme ;)

V.

**Comment by jnsh** [comment] 2020-10-28 04:30
If you have problems with packages of your chosen distribution, you should report them to the package maintainers yourself. I can't test or report issues on packages for distributions I'm not using myself for number of reasons.

Closing as downstream packaging issue. Report back if you can reproduce the problem (or have any other issues) with correctly built theme.

**Closed by jnsh** 2020-10-28 04:30 UTC
