### ISSUE TITLE
Add Arc-Lighter to Flathub for use in Flatpak apps

### ISSUE THREAD

**Issue by identithree** [jnsh/arc-theme#136] opened 2021-06-20 03:59 UTC
It would be really cool if you could add the Arc-Lighter variant to Flathub so I could use the theme with Flatpak apps. Currently, I either have to use Adwaita for Flatpak apps when I use the lighter variant or use the Arc theme which has a Flathub package but that, at least in my opinion, does not look nice.

**Comment by jnsh** [comment] 2021-06-20 13:44
I'm not maintaining any of the pre-built/distribution packages. Either way it would make more sense for the existing Arc flathub package maintainer to add the Lighter variant.

The problem is that flathub package is still building from the [original](https://github.com/horst3180/arc-theme) Arc-theme repository, instead of this maintained one, and the lighter variant is not available there. AFAIK, they have not been able to switch to this repo because of the added `inkscape` and `sassc` build dependencies (according [this issue](https://github.com/flathub/org.gtk.Gtk3theme.Arc/issues/1)). I don't know in detail how the flatpak package build process works, so I can't tell if this is still the situation.

I have a plan to avoid `inkscape` and `sassc` dependencies altogether when building from release tarballs, which should circumvent this problem. However, it's not top priority ATM, and frankly I'm still not fully certain I can get that to work..

**Comment by jnsh** [comment] 2022-01-02 18:32
With 20220102 release there should be no issues with updating the Flatpak packages, and their maintainer has been favorable as well: https://github.com/flathub/org.gtk.Gtk3theme.Arc/issues/1#issuecomment-1001836229

Closing, since there shouldn't be anything from the theme's side preventing this any more.

**Closed by jnsh** 2022-01-02 18:32 UTC
