### ISSUE TITLE
1px vertical shift between desktop view and activities overview

### ISSUE THREAD

**Issue by xoan** [jnsh/arc-theme#124] opened 2021-04-14 10:15 UTC
### Details

Some elements in top bar (status icons, weather in clock, ...) have a 1px vertical position variation between desktop view and activities overview.

- Arch Linux 5.11.13
- GNOME Shell 40.0
- Arc-theme 20210412

![Captura del escritorio de 14-04-21 09:49:52](https://user-images.githubusercontent.com/288246/114694598-3935e800-9d0a-11eb-8148-fce9e615b788.gif)

**Comment by jnsh** [comment] 2021-04-14 10:21
Sorry but I can't reproduce this.

Can you try whether this still occurs if you disable all your extensions? If that helped, re-activate the extensions one-by-one, to check which one results in this issue.

**Comment by xoan** [comment] 2021-04-14 10:43
I have the same behavior with all the extensions disabled (unless _User Themes_) and even by hidding battery percentage.

![Captura del escritorio de 14-04-21 10:28:41](https://user-images.githubusercontent.com/288246/114697898-f8d86900-9d0d-11eb-977c-ab8166742cc3.gif)

The clock button is not affected, but the activities button (three dots in this shell theme) has the same bug as status icons.

I'm using the `-solid` variant [1] in Arch Linux repositories with _Papirus_ icons, but also tested with _Adwaita_.

[1] https://archlinux.org/packages/community/any/arc-solid-gtk-theme/

**Comment by jnsh** [comment] 2021-04-14 11:00
Thank you for testing.

After some more digging, I figured out this depends on the font scaling factor: With 0.9 (which is what I've been using) there are no problems, but e.g. 0.8 or 1.0 the panel elements get jumpy..

Thank you for reporting this. I'll try to figure out a solution soon.

**Comment by liolok** [comment] 2021-04-18 08:31
It seems like a shift at first, but I noticed it's actually a vertical **shrink**. Workspace indicator would be clearer to see the change.

Also tested on `arc-gtk-theme` and it behaves them same.

**Comment by jnsh** [comment] 2021-04-20 13:28
I'm still trying to figure out the best solution to this, but reverting https://github.com/jnsh/arc-theme/commit/775abec762fdf89b236a1ee3168459d5af0b3932 should fix this if anyone wants to work around the issue locally.

**Comment by jnsh** [comment] 2021-04-25 14:50
This should now be fixed after reverting the commit mentioned above.

Closing.

**Closed by jnsh** 2021-04-25 14:50 UTC
