### ISSUE TITLE
"Unknown option --export-filename=assets/checkbox-checked.png" error during install

### ISSUE THREAD

**Issue by karlisk** [jnsh/arc-theme#28] opened 2020-03-28 20:08 UTC
I ran into an issue when trying to build and install from source on Fedora 31 as root user. Seems to be an issue with configuring during install step. I tried finding the problem in the .scss file but was unable to.

This is the configuration I tried to pass:
`# ./autogen.sh --prefix=/usr --disable-cinnamon --disable-gtk2`

This is the result when trying to install:
`# make install
Making install in common
make[1]: Entering directory '/home/user/arc-theme/common'
Making install in gtk-3.0
make[2]: Entering directory '/home/user/arc-theme/common/gtk-3.0'
Making install in 3.24
make[3]: Entering directory '/home/user/arc-theme/common/gtk-3.0/3.24'
/usr/bin/mkdir -p "light"/
echo '@import url("resource:///org/gnome/arc-theme/gtk-main.css");' > "light/gtk.css"
/usr/bin/sassc "./sass/gtk.scss" "./gtk.css"
cp "gtk.css" "light/gtk-main.css"
/usr/bin/sassc "./sass/gtk-dark.scss" "./gtk-dark.css"
cp "gtk-dark.css" "light/gtk-main-dark.css"
/usr/bin/mkdir -p "assets"/
/usr/bin/inkscape --export-id-only --export-filename="assets/checkbox-checked.png" --export-id="checkbox-checked" --export-dpi=96 "assets.svg" >/dev/null
Unknown option --export-filename=assets/checkbox-checked.png
make[3]: *** [Makefile:565: assets/checkbox-checked.png] Error 1
make[3]: Leaving directory '/home/user/arc-theme/common/gtk-3.0/3.24'
make[2]: *** [Makefile:456: install-recursive] Error 1
make[2]: Leaving directory '/home/user/arc-theme/common/gtk-3.0'
make[1]: *** [Makefile:465: install-recursive] Error 1
make[1]: Leaving directory '/home/user/arc-theme/common'
make: *** [Makefile:363: install-recursive] Error 1
`

**Comment by karlisk** [comment] 2020-03-28 20:10
Nevermind, duplicate of: https://github.com/jnsh/arc-theme/issues/26

**Comment by jnsh** [comment] 2020-03-28 20:27
I don't think this is a duplicate #26, although it is related to it.

Inkscape recently renamed the `--export-file` command line option as `--export-filename` in its development branches (`1.0.x` and `master`). This was the cause of issue #26, and was addressed with https://github.com/jnsh/arc-theme/commit/3eca62256a637a87c6e1d1e39c33b0c629cd3faa.

Looks like you are using a development version of inkscape from before the command line option changed, and therefore the `--export-filename` option isn't yet recognized. Updating inkscape to more recent development snapshot should fix the build.

If that's not reasonably possible, as a temporary workaround you can revert the build fix with:
```
git revert --no-edit 3eca62256a637a87c6e1d1e39c33b0c629cd3faa
```

I'm reopening the issue for now to keep this workaround more discoverable, as I'd image there are others that will encounter this problem as well.

**Comment by karlisk** [comment] 2020-03-28 20:43
Yeah, I closed the issue and noticed that after I looked at the simillar issue. 

FYI: Fedora 31 actually uses an older version:
`$ inkscape -V
Inkscape 1.0beta2 (unknown)`

Editing common/gtk-3.0/3.24/makefile.am to undo the commit resolved the problem. This probably will get resolved when Fedora 32 Stable releases (currently in Beta).

**Comment by jnsh** [comment] 2020-04-12 19:58
Inkscape 1.0rc1 has been released, and this particular build issue shouldn't be present with it.

Looks there's already 1.0rc1 package for Fedora 33. I hope older Fedora releases that are currently shipping inkscape 1.0 beta versions eventually catch up as well. 

Closing this, as the build now should work with both, the latest stable inkscape version (0.92), and the latest inkscape 1.0 release candidate.

**Closed by jnsh** 2020-04-12 19:58 UTC
