### ISSUE TITLE
Error (cinnamon-related) when building on GNOME

### ISSUE THREAD

**Issue by drakkar1969** [jnsh/arc-theme#2] opened 2019-06-18 11:37 UTC
- Distribution and version: 5.1.9-arch1-1-ARCH
- Versions for the affected applications/desktops/tookits: GNOME shell 3.32.2, gtk3 3.24.8

Command `./autogen.sh --prefix=/usr` fails unless the `--disable-cinnamon` option is used:

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:12: installing 'build-aux/install-sh'
configure.ac:12: installing 'build-aux/missing'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
Detected GTK3 3.24.8
Building GTK3 theme 3.20
checking for gnome-shell... yes
Detected GNOME Shell 3.32.2
Building GNOME Shell theme 3.32
checking for cinnamon... no
        
configure: WARNING: Could not find cinnamon from $PATH.
configure: error: Could not determine Cinnamon version. Install Cinnamon, or use the --with-cinnamon=<version> option. Alternatively you can choose to not build the Cinnamon theme with --disable-cinnamon option.
configure: WARNING: cache variable ac_cv_prog_CINNAMON_FOUND contains a newline

```

**Comment by jnsh** [comment] 2019-06-18 22:33
Thank you for the report.

This is essentially duplicate of issue #1, as it was about the same error for gnome-shell version.

The build failure is intended behavior, as I explained [here](https://github.com/jnsh/arc-theme/issues/1#issuecomment-496910149):
> That's how the build works by design. The build system needs to know the version for gnome-shell theme (and other versioned themes i.e. cinnamon and gtk3) to be built, and if that isn't specified with --with-gnome-shell=<version>, it tries to determine it from gnome-shell binary. If that all fails, the build fails as well to avoid issues resulting from invalid theme version.

Even for the original Arc-theme from horst3180, the build fails similarly if it the gtk3 version is unknown.

Only options for the stopping the build that I can think of would be:
1. Don't build the theme for cinnamon/gnome-shell/gtk3 at all.
2. Default to the latest available theme version.

I think the above options would result in even more confusion, as some people would be confused about missing themes, or see bugs resulting from installing the themes for wrong versions. Of couse you could add warnings to the configure, but they are very easy to miss.

I improved the build error to mention the `--with-cinnamon=` and  `--disable-cinnamon` options to address the earlier report.

If you have any other ideas for improving the situation, or the build error or documentation, let me know.

**Comment by drakkar1969** [comment] 2019-06-19 09:01
Thank you very much for the comprehensive response, I guess I should have checked the first issue before posting this :).
I'm a complete noob on the Arc build system, so I'm afraid I don't have a lot of useful input here - but maybe adding a note to the README that the build will fail (without using options) if cinnamon/gnome-shell/gtk are missing could be useful? (not that I feel strongly about it, just throwing it out there)

I also wanted to apologize for being very terse in posting my first issue. I have been contributing a little bit to the nicohood repo (gnome shell), saw the discussion re possible merge of the two repos, and decided to try your version out. I have to say that your codebase is a lot better maintained and updated compared to the nicohood repo - much easier to work with.

**Closed** 2019-06-19 10:58 UTC

**Comment by jnsh** [comment] 2019-06-20 00:19
No need to apologize. Your report had all necessary details, and I appreciate all feedback. The fact that I've received two reports for the same thing only shows that this area could use some improvement. Adding a note about this build failure to the README is a good suggestion.

Don't hesitate to report, if you notice any other issues or things that could be improved.
