### ISSUE TITLE
[gnome-3.36] blurry notifications

### ISSUE THREAD

**Issue by jnqnfe** [jnsh/arc-theme#31] opened 2020-04-12 22:33 UTC
As reported in Debian bug # 956553, with Debian Sid having switched to Gnome 3.36, notifications are now blurry. I've checked the default adwaita theme and confirmed that without arc-theme there is no issue.

I could not get attachments to work here. You can see it here: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=956553;filename=blury_notifications.png;msg=5

**Comment by jnsh** [comment] 2020-04-12 23:16
Thanks for pointing this out. I had actually noticed it before, but thought it was caused by some font rendering oddities that were present in the first 3.36.0 point release. I'll figure out a fix for this.

Thanks for the report(s).

**Closed** 2020-04-13 06:30 UTC

**Comment by jnsh** [comment] 2020-04-13 06:32
This should be now fixed in `master`. Thanks again.
